---
name: Test workflow
on:
  workflow_dispatch:
    inputs:
      arguments:
        description: Script and arguments
        required: true

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v6
      with:
        script: |
          console.log(context);
#      run: printf "%s\n" ${{ github.event.inputs.arguments }}
