---
name: Test workflow
on:
  workflow_dispatch:
    inputs:
      platform:
        required: true
        type: choice
        description: Platform
        options:
          - ubuntu-latest
          - windows-latest
          - macos-latest
      arguments:
        description: Script and arguments
        required: true

jobs:
  echo:
    runs-on: '${{ github.event.inputs.platform }}'

    steps:
    - uses: actions/github-script@v7
      with:
        script: |
          exec.exec(`printf "%s\\n" ${context.payload.inputs.arguments}`);
#      run: printf "%s\n" ${{ github.event.inputs.arguments }}
